version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lms_postgres
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms_network

volumes:
  postgres_data:

networks:
  lms_network:
    driver: bridge
